FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Spider Log API
Provides services for the spider log app family, recording the world's spider sightings

# Group Spiders
Access to Spider resources

## My Spiders [/spiders{?page,size}]
### Get all my spider sightings [GET]
+ Parameters
    + page (required, number, `1`)... `page`    number
    + size (required, number, `10`)...     `page`   size
+ Request

    + Header
        
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0

+ Response 200 (application/json)
    
    + Header
        
            ETag: "euyfewuysdfsdf"
            cach-control: max-age=600

    + Body
    
            {
                "page" :
                {
                    "number" : 1,
                    "size" : 10,
                    "totalPages" : 20
                },
                "spiders" :
                [
                    {
                        "sightedAt" : "2015-08-29T19:30",
                        "imageUrl" : "uid:34225/4699046e5d_z.jpg",
                        "description" : "Spider I saw at home",
                        "tags" : [
                            "big"
                        ]
                    },
                    {
                        "sightedAt" : "2015-08-21T19:30",
                        "imageUrl" : "uid:34225/4699046e5e_z.jpg",
                        "description" : "Spider I saw at office",
                        "tags" : [
                            "scary"
                        ]
                    },
                    {
                        "sightedAt" : "2015-05-23T19:30",
                        "imageUrl" : "uid:34225/4699046e5r_z.jpg",
                        "description" : "Spider I saw at beach",
                        "tags" : [
                            "sandy"
                        ]
                    }
                ]
            }